name: Format Code

on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [main]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Format code with Black
        run: poetry run black .

      - name: Check for changes
        run: git diff --exit-code
